# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql
  database: oss_dashboard
  username: rails
  password: <%= begin IO.read("/usr/local/www/rcos_dashboard/.db") rescue "" end %>


cucumber:
  <<: *TEST